### PR TITLE
Changes for version 16 and above acl checks were refactored in the server. 

### PR DESCRIPTION
**Pull request by davecramer**
Issue #, if available:

Description of changes:

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by jkatz** [comment]
@davecramer would it be possible to put this change in compatibility.h and use that to incorporate the updated function definition?

**Comment by davecramer** [comment]
> @davecramer would it be possible to put this change in compatibility.h and use that to incorporate the updated function definition?

Of course. However there are already a number of places where we check for version numbers. I was copying the existing code. I could see using macros though.

**Comment by jconway** [comment]
Agree with Jonathan. At one point I think all of the version dependencies were centralized in compatibility.h. IMHO, to the extent that has eroded over time, it should be fixed rather than continued.

**Comment by davecramer** [comment]
fair enough

**Review by jkatz — APPROVED** [review]

**Pull request merged**
