### PR TITLE
Record dependency of a TLE on its control and sql functions

### PR DESCRIPTION
**Pull request by formalLogicGirl**
Issue #, if available:
#44 

Description of changes:

Record dependency of an extension installed by pg_tle on its control function and sql function, when the extension is created. This is in for pg_dump to correctly create the control and sql functions before creating the extension. Otherwise, the default order of object creation by pg_dump is to create functions after extensions, so that restoring from a dump will fail to create TLE-installed extensions.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by jkatz** [comment]
@formalLogicGirl Can you add a test? I believe this would be through the TAP tests.

**Comment by formalLogicGirl** [comment]
> @formalLogicGirl Can you add a test? I believe this would be through the TAP tests.

Yes. I'll add tap tests as a separate PR, after I get the full workflow of restoring from dump well tested. Don't want to hold up too much stuff into one. I'll have multiple PRs for this issue.

**Comment by formalLogicGirl** [comment]
@jconway Is there a better way to get function OID? I'm using SPI. Something similar to SearchSysCache() thats exposed for extension code to call?

**Comment by formalLogicGirl** [comment]
> @jconway Is there a better way to get function OID? I'm using SPI. Something similar to SearchSysCache() thats exposed for extension code to call?

will use LookupFuncName() and update this PR. Thanks.

**Comment by formalLogicGirl** [comment]
As an alternative to SPI_execute to look up function oids, I tried the following

```
        char *qualifiedCtlNameStr = psprintf("%s.%s.control", PG_TLE_NSPNAME, extname);
        ctlFuncId = LookupFuncName(stringToQualifiedNameList(qualifiedCtlNameStr), 0, NULL, false /* missing_ok */);
```

However, that doesn't work because pgtle.extname.control is parsed as database name pgtle, schema name extname, function name control. Having . in the function name, which is not disallowed by postgres, causes ambiguity in parsing a schema-qualified name in the postgres functions used here.

**Review by jkatz — APPROVED** [review]

**Comment by formalLogicGirl** [comment]
This fixes one of the ordering problems in pg_dump generated TOC. There are some more problems for the pg_dump/pg_restore workflow to work, and I'm continuing to investigate and work on them in #154 and get #152 to work. This PR contributes one part of #44

**Comment by formalLogicGirl** [comment]
Closed by the following

https://github.com/aws/pg_tle/pull/151 - pg_dump working with pg_tle
https://github.com/aws/pg_tle/pull/155 - pg_restore working with pg_tle
https://github.com/aws/pg_tle/pull/157 - test
https://github.com/aws/pg_tle/pull/156 - doc update

**Pull request merged**
